import os

BASE_DIR = os.path.dirname(__file__)
ASSETS_PATH = os.path.join(BASE_DIR, 'assets')

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

SCROLL_SPEED = 3
ENEMY_SPEED = 4
LASER_SPEED = 14
PLAYER_SPEED = 6
ENEMY_SPAWN_CHANCE = 0.018
POINTS_PER_KILL = 10
LEVEL_UP_THRESHOLD = 250
