import os

BASE_DIR = os.path.dirname(__file__)
ASSETS_PATH = os.path.join(BASE_DIR, 'assets')

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

SCROLL_SPEED = 3
ENEMY_SPEED = 4
STRONG_ENEMY_SPEED = 2
LASER_SPEED = 14
ENEMY_BULLET_SPEED = 5
PLAYER_SPEED = 6
ENEMY_SPAWN_CHANCE = 0.018
STRONG_ENEMY_SPAWN_CHANCE = 0.005
POINTS_PER_KILL = 10
STRONG_ENEMY_POINTS = 30
LEVEL_UP_THRESHOLD = 250
